<a href="https://colab.research.google.com/github/komisarzGiT/gai/blob/main/UG_ML01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Marcin Byra  
Class: 2526-1MAO2  
Student ID: 25258161

The objective is to present end to end process of machine learning model training and evaluation based on provided train and test data sets.  

ML aghoritms must include Decision Tree classifiers:

*   Gini
*   Information Gain
*   Gain ratio

as well as either KNN or Random Forest. KNN was chosen for this report to work with distinct alghoritms, since random forest is based on decision tree method.

In [114]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#install c45 iblary
!pip install -U c45-decision-tree #https://pypi.org/project/c45-decision-tree/

In [115]:
#two files are provided containing respecively train and test data sets
train_data = 'https://raw.githubusercontent.com/komisarzGiT/gai/refs/heads/main/GU_ML01/Assignment1/EEG_Train_Binary.csv'
test_data = 'https://raw.githubusercontent.com/komisarzGiT/gai/refs/heads/main/GU_ML01/Assignment1/EEG_Test_Binary.csv'

df_train = pd.read_csv(train_data)
df_test = pd.read_csv(test_data)

#check data types
print(f"Data types in training set \n{df_train.dtypes}")
print(f"\nData types in testing set \n{df_test.dtypes}")


Data types in training set 
X1     int64
X2     int64
X3     int64
X4     int64
X5     int64
X6     int64
X7     int64
X8     int64
X9     int64
X10    int64
X11    int64
X12    int64
X13    int64
X14    int64
X15    int64
X16    int64
y      int64
dtype: object

Data types in testing set 
X1     int64
X2     int64
X3     int64
X4     int64
X5     int64
X6     int64
X7     int64
X8     int64
X9     int64
X10    int64
X11    int64
X12    int64
X13    int64
X14    int64
X15    int64
X16    int64
y      int64
dtype: object


In [116]:
train_rows, train_columns = df_train.shape
print(f"Training data set has {train_rows} observations and {train_columns} variables. Sample data:")
display(df_train.head(3))

test_rows, test_columns = df_test.shape
print(f"\nTraining data set has {test_rows} observations and {test_columns} variables. Sample data:")
display(df_test.head(3))

Training data set has 3171 observations and 17 variables. Sample data:


X1   X2   X3  X4  X5   X6   X7   X8   X9  X10  X11  X12  X13  X14  X15  \
0   41   32  -27 -51 -89 -117  -83  -35   25   33   27   33   -9  -38  -57   
1 -281 -234 -166 -93 -22   55  109  137  115   80   54   50   37   -3  -53   
2    2   -1  -11 -32 -44  -44  -35  -23   -8   -7  -14  -15   -2   17   19   

   X16  y  
0  -87  0  
1 -111  0  
2    7  0


Training data set has 829 observations and 17 variables. Sample data:


X1  X2  X3  X4   X5   X6  X7  X8  X9  X10  X11  X12  X13  X14  X15  X16  y
0   68  46  26  11   28   57  45  23  83   93   35   30   38   26    4   21  0
1  104  32  26  11   -8   -3  26  43  31   56   73   -1  -25  -35  -81 -137  0
2  -81 -24  40  91  103  103  84  52  -3  -65 -120 -171 -194 -193 -162 -102  0

In [117]:
#check for missing values and outliers
print(f"\nSummary statistics to check for missing values and outliers in training data")
display(df_train.describe().round(2).T)

print(f"\nSummary sStatistics to check for missing values and outliers in test data")
display(df_test.describe().round(2).T)


Summary statistics to check for missing values and outliers in training data


count  mean    std    min   25%  50%   75%    max
X1   3171.0 -6.06  49.55 -281.0 -14.5  0.0   8.0  244.0
X2   3171.0 -5.97  49.52 -255.0 -17.0 -1.0  10.0  261.0
X3   3171.0 -6.09  48.90 -255.0 -12.5 -1.0   7.0  238.0
X4   3171.0 -5.89  49.28 -257.0 -18.0 -2.0  12.0  246.0
X5   3171.0 -6.18  49.69 -262.0 -24.0 -1.0  13.0  249.0
X6   3171.0 -5.93  49.37 -277.0 -18.0 -1.0  10.0  229.0
X7   3171.0 -6.13  49.31 -277.0 -15.0 -1.0   9.0  205.0
X8   3171.0 -6.22  50.28 -260.0 -19.0 -2.0  11.0  201.0
X9   3171.0 -6.55  50.72 -290.0 -18.0 -1.0   8.0  225.0
X10  3171.0 -7.00  51.28 -302.0 -21.0 -1.0  10.0  227.0
X11  3171.0 -7.45  50.78 -266.0 -15.5 -1.0   7.0  262.0
X12  3171.0 -7.52  51.04 -266.0 -20.0 -2.0  10.0  283.0
X13  3171.0 -7.54  51.25 -254.0 -24.0 -1.0  12.0  296.0
X14  3171.0 -8.00  50.33 -290.0 -20.0 -2.0   9.0  291.0
X15  3171.0 -7.78  50.07 -323.0 -18.0 -2.0   8.0  244.0
X16  3171.0 -7.38  49.82 -317.0 -14.0 -1.0   5.0  258.0
y    3171.0  0.51   0.50    0.0   0.0  1.0   1.0    1.0


Summary sStatistics to check for missing values and outliers in test data


count  mean    std    min   25%  50%   75%    max
X1   829.0 -6.44  49.62 -195.0 -23.0 -1.0   8.0  252.0
X2   829.0 -7.36  50.78 -221.0 -23.0 -3.0  10.0  241.0
X3   829.0 -7.04  51.50 -220.0 -17.0 -2.0   8.0  222.0
X4   829.0 -6.75  51.96 -204.0 -21.0 -2.0  13.0  222.0
X5   829.0 -6.13  53.17 -264.0 -25.0 -1.0  17.0  228.0
X6   829.0 -6.02  53.40 -260.0 -19.0 -2.0  11.0  245.0
X7   829.0 -6.14  53.51 -237.0 -16.0 -2.0   9.0  220.0
X8   829.0 -7.12  54.20 -254.0 -22.0 -2.0  11.0  271.0
X9   829.0 -6.63  53.78 -248.0 -21.0 -1.0  10.0  280.0
X10  829.0 -5.72  53.52 -232.0 -21.0  0.0  12.0  251.0
X11  829.0 -5.28  51.04 -276.0 -14.0 -1.0   8.0  196.0
X12  829.0 -4.85  50.55 -306.0 -19.0 -1.0  13.0  186.0
X13  829.0 -4.66  50.02 -288.0 -21.0 -1.0  13.0  157.0
X14  829.0 -5.41  49.48 -237.0 -19.0 -1.0  11.0  204.0
X15  829.0 -6.28  50.39 -214.0 -18.0 -2.0  10.0  251.0
X16  829.0 -7.67  51.35 -220.0 -17.0 -1.0   5.0  270.0
y    829.0  0.47   0.50    0.0   0.0  0.0   1.0    1.0

In [118]:
#split explanatory variables from target variables
X_train = df_train.drop('y', axis=1) #explanatory
y_train = df_train['y'] #target

X_test = df_test.drop('y', axis=1)
y_test = df_test['y']


In [119]:
#count number of distinct values for all features
train_count_distinct = X_train.nunique()
print(f"Average number of distinct values across all features in training data set is: \n {train_count_distinct.mean()}")
print(f"\nCount of distinct values per feature \n{train_count_distinct}")

test_count_distinct = X_test.nunique()
print(f"\nAverage number of distinct values across all features in training data set is: \n {test_count_distinct.mean()}")
print(f"\nCount of distinct values per feature \n{test_count_distinct}")

Average number of distinct values across all features in training data set is: 
 325.6875

Count of distinct values per feature 
X1     322
X2     332
X3     321
X4     329
X5     323
X6     320
X7     322
X8     325
X9     330
X10    334
X11    330
X12    327
X13    327
X14    320
X15    326
X16    323
dtype: int64

Average number of distinct values across all features in training data set is: 
 220.75

Count of distinct values per feature 
X1     221
X2     219
X3     218
X4     217
X5     218
X6     227
X7     228
X8     223
X9     233
X10    223
X11    215
X12    216
X13    218
X14    221
X15    221
X16    214
dtype: int64


In [120]:
#Below code is based on lecture
#CT5148 Programming and Tools for Artificial Intelligence - Online
#by Dr James McDermott, University of Galway
#Week 5: scikit-learn

#Training and evaluating decision trees

from sklearn.tree import DecisionTreeClassifier
from C45 import C45Classifier

# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html
# criterion{“gini”, “entropy”, “log_loss”}, default=”gini”
# The function to measure the quality of a split. Supported criteria are “gini” for the Gini impurity and “log_loss” and “entropy” both for the Shannon information gain, see Mathematical formulation.

# Train DT Gini
dt_gini = DecisionTreeClassifier(criterion='gini', random_state=7)
dt_gini.fit(X_train, y_train)

# Evaluate DT Gini
accuracy_gini = dt_gini.score(X_test, y_test)
print(f"Accuracy DT Gini: {accuracy_gini:.4f}")

# Train DT Inf Gain
dt_inf_gain = DecisionTreeClassifier(criterion='entropy', random_state=7)
dt_inf_gain.fit(X_train, y_train)

# Evaluate DT Inf Gain
accuracy_inf_gain = dt_inf_gain.score(X_test, y_test)
print(f"Accuracy DT Information Gain: {accuracy_inf_gain:.4f}")

#Train DT Inf Gain Ratio
dt_inf_gain_ratio = C45Classifier()
dt_inf_gain_ratio.fit(X_train, y_train)

#Evaluate DT Inf Gain Ratio
y_pred_inf_gain_ratio = pd.Series(dt_inf_gain_ratio.predict(X_test))  #predict returned list, converting to series
total_matches = (y_test == y_pred_inf_gain_ratio).sum()
accuracy_inf_gain_ratio = total_matches / len(y_test)
print(f"Accuracy DT Information Gain Ratio: {accuracy_inf_gain_ratio:.4f}")

#dt_inf_gain_ratio.evaluate(X_test, y_test)



Accuracy DT Gini: 0.9952
Accuracy DT Information Gain: 0.9964
Accuracy DT Information Gain Ratio: 0.8094


In [121]:
#calculate confusion matrix for additional context
from sklearn.metrics import confusion_matrix

# CM for Gini
print("Confusion Matrix for DT Gini")
y_pred_gini = dt_gini.predict(X_test)
print(confusion_matrix(y_test, y_pred_gini))

#CM for Inf Gain
print("\nConfusion Matrix for DT Inf Gain")
y_pred_inf_gain = dt_inf_gain.predict(X_test)
print(confusion_matrix(y_test, y_pred_inf_gain))

# CM for Inf Gain Ratio
print("\nConfusion Matrix for DeT Inf Gain Ratio")
print(confusion_matrix(y_test, y_pred_inf_gain_ratio))

Confusion Matrix for DT Gini
[[439   4]
 [  0 386]]

Confusion Matrix for DT Inf Gain
[[440   3]
 [  0 386]]

Confusion Matrix for DeT Inf Gain Ratio
[[305 138]
 [ 20 366]]


In [122]:
#Below code is based on lecture
#CT5148 Programming and Tools for Artificial Intelligence - Online
#by Dr James McDermott, University of Galway
#Week 5: scikit-learn

# KNN algoritm needs standarization of values across dimesions based on training
# data set scikit-learn StandardScaler uses z-scaling to scale date
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# standardize training and test data
scaler = StandardScaler() #z-scaling using std dev and mean
X_train_std = scaler.fit_transform(X_train) #derive mean and std dev from X_train and apply
X_test_std = scaler.transform(X_test) #apply X_train mean and std dev standardization to X_test

#list of k values to test
k_values = [1, 3, 5, 9, 15, 21, 49, 101]

print("Training and evaluating KNN:")

accuracy_knn_max = 0
for k in k_values:
    # Train KNN model
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_std, y_train)

    # Evaluate
    y_pred_knn = knn.predict(X_test_std)
    total_matches_knn = (y_test == y_pred_knn).sum()
    accuracy_knn = (total_matches_knn / len(y_test))
    print(f"Accuracy with KNN (k={k}): {accuracy_knn:.4f}")
    if accuracy_knn_max < accuracy_knn:
      accuracy_knn_max = accuracy_knn
      k_best = k

print(f"\nBest KNN accuracy is {accuracy_knn_max:.4f} achieved for k={k_best} ")


Training and evaluating KNN:
Accuracy with KNN (k=1): 0.9964
Accuracy with KNN (k=3): 0.9952
Accuracy with KNN (k=5): 0.9916
Accuracy with KNN (k=9): 0.9879
Accuracy with KNN (k=15): 0.9807
Accuracy with KNN (k=21): 0.9795
Accuracy with KNN (k=49): 0.9578
Accuracy with KNN (k=101): 0.9252

Best KNN accuracy is 0.9964 achieved for k=1 


In [123]:
#table with result summary
summary_data = {
    ' ':      ['Decision Tree Gini                  ',
              'Decision Tree Information Gain      ',
              'Decision Tree Information Gain Ratio',
              'K-Nearest Neighbors (k=1)           '],
    'Accuracy': [accuracy_gini,
                 accuracy_inf_gain,
                 accuracy_inf_gain_ratio,
                 accuracy_knn_max] # KNN k=1
}

summary_df = pd.DataFrame(summary_data)
print(summary_df.to_string(index=False)) #string to remove df index

                                      Accuracy
Decision Tree Gini                    0.995175
Decision Tree Information Gain        0.996381
Decision Tree Information Gain Ratio  0.809409
K-Nearest Neighbors (k=1)             0.996381
