<center><img src=img/MScAI_brand.png width=70%></center>

# Numpy: Broadcasting



In [1]:
import numpy as np
x = np.array([[1, 2],
              [3, 4]])
x + 10 # how?!

array([[11, 12],
       [13, 14]])

### Element-wise operations

As we know, many Numpy operations work *per-element*. A binary operation like `*` is straightforward when the two inputs are the same shape:

In [3]:
X = np.array([[1.0,  2.0,   3.0], 
              [4.0,  5.0,   6.0]])
Y = np.array([[0.01, 0.1,   1.0], 
              [10.0, 100.0, 1000.0]])
print(X * Y) 

[[1.e-02 2.e-01 3.e+00]
 [4.e+01 5.e+02 6.e+03]]


That is sometimes called the *element-wise* product or *Hadamard product*. It requires the arrays to have the same size and shape. 

### Broadcasting


Element-wise operations are straightforward when the operands have the same shape.

Numpy also allows multiplication or other functions to work when the two array shapes are different, if they are *broadcastable*. 

In [9]:
A = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8]])
B = np.array([10, 11, 12, 13])
C = A + B
print(f"A.shape = {A.shape}")
print(f"B.shape = {B.shape}")
print(f"C.shape = {C.shape}")
print(f"C = ")
print(C)


A.shape = (2, 4)
B.shape = (4,)
C.shape = (2, 4)
C = 
[[11 13 15 17]
 [15 17 19 21]]


What are the rules here? 

The data in the array with a smaller dimension is **broadcast** ('reused') across that with a larger dimension so that they have compatible shapes.  We line the shapes up from the right and look at corresponding dimensions. If they're equal, or one is equal to 1, or one is not present, then it's allowed:

```
A      (2d array):  2 x 4
B      (1d array):      4
Result (2d array):  2 x 4
```

A contrived example:
```
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```

Here's an example where broadcasting is not allowed:

In [23]:
A = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8]]); print(A.shape)
B = np.array([10, 11]); print(B.shape)
C = A + B

(2, 4)
(2,)


ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

```
A      (2d array):  2 x 4
B      (1d array):      2
Result           :  incompatible
```

We can make the above work with a `reshape`:

In [24]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]); print(A.shape)
B = np.array([10, 11]).reshape(2, 1); print(B.shape)
C = A + B
print(C)
print(C.shape)

(2, 4)
(2, 1)
[[11 12 13 14]
 [16 17 18 19]]
(2, 4)


```
A      (2d array):  2 x 4
B      (1d array):  2 x 1
Result (2d array):  2 x 4
```

The full rules: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

### Matrix multiplication

All of the above is about *element-wise* operations.

There is also true matrix multiplication, where the two matrices must be of *compatible* shapes (not the same thing as *broadcastable*). In the following case they are $3\times 2$ and $2\times 4$. They are compatible because the "inner values" are the same, ie $2$. Numpy allows the `@` operator for this.

In [11]:
X = np.array([[1.0, 2.0], 
              [3.0, 4.0], 
              [5.0, 6.0]])
Y = np.array([[1.0, 1.0, 1.0, 1.0], 
              [10.0, 10.0, 10.0, 10.0]])
print(X.shape, Y.shape)
C = X @ Y
print(C)
print(C.shape)

(3, 2)
(2, 4)
[[21. 21. 21. 21.]
 [43. 43. 43. 43.]
 [65. 65. 65. 65.]]
(3, 4)
[[21. 21. 21. 21.]
 [43. 43. 43. 43.]
 [65. 65. 65. 65.]]
